name: "Release new version"
on:
    push:
        branches:
            - main

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Create version
              id: create_version
              uses: mathieudutour/github-tag-action@v5.5
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
            - name: "Write changelog"
              run: |
                CHANGELOG=""
                if [ -e CHANGELOG ]
                then
                    CHANGELOG=$(cat CHANGELOG)
                fi
                echo -e "${{steps.create_version.outputs.changelog}}\n\n${CHANGELOG}" > CHANGELOG
            - name: "Commit"
              uses: EndBug/add-and-commit@v7.2.1
              with:
                message: 'chore: bumping version and storing changelog'
                push: false
            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v3
