name: "Release new version"

on:
    push:
        branches:
            - main

jobs:
    release:
        if: "${{ github.event.head_commit.message != 'chore: bumping version and storing changelog' }}"
        name: Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
                token: ${{ secrets.DEPLOYMENT_TOKEN }}
            - name: Create version
              id: create_version
              uses: mathieudutour/github-tag-action@v5.5
              with:
                tag_prefix: ""
                github_token: ${{ secrets.DEPLOYMENT_TOKEN }}
            - name: "Write changelog"
              run: |
                CHANGELOG=""
                if [ -e CHANGELOG.md ]
                then
                    CHANGELOG=$(cat CHANGELOG.md)
                fi
                echo -e "${{steps.create_version.outputs.changelog}}\n\n${CHANGELOG}" > CHANGELOG.md
            - name: "Commit"
              uses: EndBug/add-and-commit@v7.2.1
              with:
                message: 'chore: bumping version and storing changelog'
                push: true
            - name: Create a GitHub release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
              with:
                tag_name: ${{ steps.create_version.outputs.new_tag }}
                release_name: ${{ steps.create_version.outputs.new_tag }}
                body: ${{ steps.create_version.outputs.changelog }} 
